### ISSUE TITLE
This is a warning to you, from GalacticFantasy#0001, You are being targeted from hackers off the dark web, other hackers, and the discord officials to get banned from discord. You have messed up

### ISSUE THREAD

**Issue by AnonymousMonke12** [jona939s/Trail-monkey#1]
This is a warning to you, from GalacticFantasy[#0001](https://www.youtube.com/hashtag/0001), You are being targeted from hackers off the dark web, other hackers, and the discord officials to get banned from discord. You have messed up

**Comment by JJoeDev** [comment]
Sure thing buddy :D
